### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by drewfreyling** [GlobalX/PockyBot.NET#11]
Assuming GNU General Public License v3.0 as per https://github.com/GlobalX/pockybot/blob/master/LICENSE?

**Comment by Chromadream** [comment]
Opinion: I'm not a big fan of licensing a library with GPL for some reasons:

* Ambiguity on static linking with applications running on different license. Implication: our runtime deployment have to be opensourced too.
* Looks like the base library [GlobalX.ChatBots.Core](https://github.com/GlobalX/GlobalX.ChatBots.Core) is licensed on MIT, which means that it doesn't make too much sense for the derivative work to be on a more restrictive license.

Recommendation: MIT, or if we want to stay on GPL-family, LGPLv3.
