### ISSUE TITLE
Pegs with double newlines fail on entry

### ISSUE THREAD

**Issue by jimcullenaus** [GlobalX/PockyBot.NET#168]
When entering a message with multiple consecutive newlines, the bot fails to send the peg. Logs say "System.ArgumentException: Html has more levels than expected".

This may be the result of transformations the Webex client makes to a user's typed text before sending it.

An example message (as typed by a user):

```
@PockyBot peg @User
message line one
message line two

message line three
```

**Comment by Lauraducky** [comment]
This bug will be related to GlobalX.ChatBots,WebexTeams rather than with PockyBot itself

**Comment by Lauraducky** [comment]
Fixed by https://github.com/GlobalX/GlobalX.ChatBots.WebexTeams/pull/50
