### ISSUE TITLE
Implement winners trigger

### ISSUE THREAD

**Issue by Evangelinexx** [GlobalX/PockyBot.NET#30]

**Comment by jimcullenaus** [comment]
I wonder, what is the value in this?

**Comment by Evangelinexx** [comment]
I put this here mostly because it is in old PockyBot, but I like the question - I think if it's not needed, we shouldn't go to the effort of implementing this.

**Comment by Lauraducky** [comment]
I actually completely forgot that this trigger existed. Could be useful instead of results for "previewing" the number of snacks required, but I'm not totally sold on the need to preview anyway.

**Comment by Lauraducky** [comment]
I do think that we need to think hard about what triggers we want in general. There were so many in the old version that didn't see use that we might think about leaving out

**Comment by jimcullenaus** [comment]
> Could be useful instead of results for "previewing" the number of snacks required

The reason I think results is better is that it allows you to see likely last minute changes and plan accordingly. For example someone who would be winner except they haven't, at the time of calling (which is usually a couple of hours before TIK), spent all of their pegs.

**Comment by Evangelinexx** [comment]
Is there anyone here who disagrees if I just close this one and we leave it out for the first release of PockyBot.NET?

**Comment by jimcullenaus** [comment]
Sounds good to me.
