### ISSUE TITLE
Update usernames before finish

### ISSUE THREAD

**Issue by Evangelinexx** [GlobalX/PockyBot.NET#34]
When a user with sufficient permissions calls "@PockyBot finish", the bot should update all usernames before formatting the results, to ensure it has the most up-to-date information.

**Comment by Lauraducky** [comment]
Names are now updated both on giving and receiving pegs, so this trigger isn't necessarily as useful as it once was. @jimcullenaus suggested performing the update functionality on calling the finish trigger.
